name:                synchronous-shopping 
version:             1.0.0.0
author:              Author name here
maintainer:          example@example.com
copyright:           "MIT"

dependencies:
  - base
  - containers
  - PSQueue
  - extra
  - monoidal-containers
  - pretty-simple
  - text
  - derivingvia-extras
  - graphviz
  - multiset
  - unordered-containers
executable:
  dependencies:
    - synchronous-shopping
  main: app/Main.hs
library:
#  exposed-modules:
#    PiorityQueue
  source-dirs: src
