name:                synchronous-shopping 
version:             1.0.0.0
author:              Author name here
maintainer:          example@example.com
copyright:           "MIT"

dependencies:
  - base
  - containers
  - text
  - unordered-containers
  - bytestring
  - array
  - hashable
  - graphviz
  - hashtables
executable:
  dependencies:
    - synchronous-shopping
  main: app/Main.hs
library:
  #  exposed-modules:
  #  PairHeap
  source-dirs: src
